#!/usr/bin/env bash
# shellcheck disable=SC2016 # the fixture and its assertions are markdown, backticks and all
set -uo pipefail

HARNESS_SOURCE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

. "$HARNESS_SOURCE/vendor-skills.sh"
set +e # the script it just sourced runs under `set -e`; this file collects failures instead

failures=0

pass() { printf 'ok   %s\n' "$1"; }

fail() {
  printf 'FAIL %s\n' "$1" >&2
  failures=$((failures + 1))
}

assert_contains() {
  if grep -qF -- "$2" "$fixture/SKILL.md"; then pass "$1"; else fail "$1"; fi
}

assert_file_contains() {
  if grep -qF -- "$3" "$fixture/$2"; then pass "$1"; else fail "$1"; fi
}

fixture=$(mktemp -d)
trap 'rm -rf -- "$fixture"' EXIT

cat >"$fixture/SKILL.md" <<'EOF'
---
name: implement
description: Build a thing. Hand off to /handoff when done.
---

Use `/handoff` where possible, then use /handoff to compact the work.
Run `/compact` when the context fills up.
Route each issue through `/handoff` first.
The handler lives in src/handoff/handler.ts, per `docs/agents/handoff-labels.md`.
The throwaway route under `/handoff/<name>` mounts the same switcher.
A retired skill keeps its bare name: /code-review and `/diagnosing-bugs` stay put.
Deploy it with `/use-railway`, then check /use-railway for the logs.
Call the Skill tool twice, for "grilling" and "domain-modeling".
Then call the Skill tool with "research" and `prototype`.
The glossary labels "research" as an investigation type.
A retired dispatch says to call the Skill tool with "implement".
EOF

# A skill body is not always markdown. A skill that ships a `template.sh` naming a slash command
# needs the rewrite there too, or a markdown-only rewrite would install a reference that dispatches
# to nothing.
cat >"$fixture/template.sh" <<'EOF'
#!/usr/bin/env bash
# Generated by the /handoff skill.
# Hand the captured values to `/handoff`. Stages live under /handoff/stages.
EOF

apply_prefix_to_references "$fixture"

assert_contains "a backticked reference is prefixed" 'Use `/matt-handoff` where possible'
assert_contains "a bare reference is prefixed" 'use /matt-handoff to compact'
assert_contains "a reference in the frontmatter description is prefixed" \
  'Hand off to /matt-handoff when done'
assert_contains "a reference whose name also appears in paths is prefixed" '`/matt-handoff` first'
assert_contains "two quoted Skill tool dispatches are prefixed" \
  'Call the Skill tool twice, for "matt-grilling" and "matt-domain-modeling"'
assert_contains "a single quoted Skill tool dispatch is prefixed" \
  'call the Skill tool with "matt-research" and `matt-prototype`'
assert_contains "a quoted skill label outside dispatch prose is left alone" \
  'The glossary labels "research" as an investigation type'
assert_contains "a non-vendored Skill tool dispatch is left alone" \
  'call the Skill tool with "implement"'

assert_contains "a built-in Claude Code command is left alone" 'Run `/compact` when'
assert_contains "a path ending in a skill name is left alone" 'src/handoff/handler.ts'
assert_contains "a backticked path is left alone" '`docs/agents/handoff-labels.md`'
assert_contains "a route starting with a skill name is left alone" '`/handoff/<name>`'

# A skill the harness stopped vendoring is no longer in UPSTREAM_SKILLS, so its name is somebody
# else's now. Prefixing it would install a reference that dispatches to nothing.
assert_contains "a retired skill name is left alone" \
  '/code-review and `/diagnosing-bugs` stay put'

assert_file_contains "a bare reference in a shell file is prefixed" template.sh \
  'Generated by the /matt-handoff skill'
assert_file_contains "a backticked reference in a shell file is prefixed" template.sh \
  '`/matt-handoff`'
assert_file_contains "a path in a shell file is left alone" template.sh '/handoff/stages'

# The exception to the prefix rule, driven rather than assumed. `use-railway` is the name Railway's
# own installer writes, so a rewrite to `matt-use-railway` or `railway-use-railway` would leave the
# CLI refilling the unprefixed name for the harness to purge — the ping-pong #60 exists to end.
# The rewrite skips it because it is absent from UPSTREAM_SKILLS, which is a property of a list a
# future agent can extend by hand: add `use-railway` to it and both of these go red, which is the
# only reason they are worth writing.
assert_contains "the prefix rewrite leaves a backticked /use-railway alone" '`/use-railway`'
assert_contains "the prefix rewrite leaves a bare /use-railway alone" 'check /use-railway for'

# What makes the rewrite skip it: the loop that renames a directory, its `name:` frontmatter and its
# cross-references walks UPSTREAM_SKILLS alone. That is a hand-kept list, and adding this name to it
# is the one edit that would silently start prefixing the skill, so the list is what is asserted.
if printf '%s\n' "${UPSTREAM_SKILLS[@]}" | grep -qx "$RAILWAY_SKILL"; then
  fail "$RAILWAY_SKILL is not in the set the prefix rewrite renames"
else
  pass "$RAILWAY_SKILL is not in the set the prefix rewrite renames"
fi

# The vendored artifact itself, not a fixture: a fixture written by this file and grepped by this
# file would agree with itself no matter what the vendor did. This is the file install.sh ships, and
# the name in it is what Claude Code registers the skill under — a re-vendor that prefixed it, by
# hand or by adding it to the list above, lands here.
railway_vendored="$HARNESS_SOURCE/skills/$RAILWAY_SKILL/SKILL.md"

if [ -f "$railway_vendored" ] && grep -qx "name: $RAILWAY_SKILL" "$railway_vendored"; then
  pass "the vendored $RAILWAY_SKILL declares the unprefixed name Railway's installer writes"
else
  fail "the vendored $RAILWAY_SKILL declares the unprefixed name Railway's installer writes"
fi

if [ -d "$HARNESS_SOURCE/skills/$PREFIX$RAILWAY_SKILL" ]; then
  fail "$RAILWAY_SKILL is vendored under no prefixed directory name"
else
  pass "$RAILWAY_SKILL is vendored under no prefixed directory name"
fi

if [ "$failures" -eq 0 ]; then
  echo "prefix-rewrite: all assertions passed"
else
  printf 'prefix-rewrite: %d assertion(s) failed\n' "$failures" >&2
  exit 1
fi
